class Option {
    value
    text

    constructor(text, value) {
        this.value = value;
        this.text = text;
    }
}

const options = {
    default: [
        new Option("Ownership :)", "ownership"),
        new Option("Rent", "rent"),
        new Option("Given", "given"),
    ],
    has_nationality : [
        new Option("No", "no"),
        new Option("Jnesiye ajnabiye w lebneniye", "lebniniye_and_another"),
        new Option("Lebanese only", "lebanese"),
        new Option("Foreigner only", "foreigner"),
        new Option("Hamel jensiye ajnabiye w taht l kayd b lebnen", "taht_kayd"),
    ],

    nationality_type_id : [
        new Option("Lebanese", "lebanese"),
        new Option("Lebnene bl tajanos", "lebnene_mjannas"),
        new Option("Foreigner and Lebanese", "foreigner_and_lebanese"),
        new Option("Foreigner", "foreigner"),
        new Option("No nationality", "no_nationality"),
    ],
    country_divorced: [
        new Option("Lebanon", "Lebanon"),
        new Option("Other", "Other"),
    ],
    divorce_msabbat: [
        new Option("idk", "idk"),
        new Option("Yes", "yes"),
        new Option("No", "no"),
    ],
    divorce_msajal: [
        new Option("idk", "idk"),
        new Option("Yes", "yes"),
        new Option("No", "no"),
    ],
    hadane: [
        new Option("Father", "father"),
        new Option("Mother", "mother"),
        new Option("Moshtarake", "moshtarake"),
    ],
    marriage_status: [
        new Option("Yes", "yes"),
        new Option("Zawj aw Zawja dead", "widowed"),
        new Option("Divorced", "divorced"),
    ],
    nationalities: [
        new Option("Lebanon", "lebanon"),
        new Option("Syria", "syria"),
    ],
    sex: [
        new Option("Male", "male"),
        new Option("Female", "female"),
        new Option("Other", "other"),
    ],
    country_of_birth : [
        new Option("Afghanistan", "afghanistan"),
        new Option("Albania", "albania"),
        new Option("Algeria", "algeria"),
        new Option("Andorra", "andorra"),
        new Option("Angola", "angola"),
        new Option("Anguilla", "anguilla"),
        new Option("Antarctica", "antarctica"),
        new Option("Argentina", "argentina"),
        new Option("Armenia", "armenia"),
        new Option("Australia", "australia"),
        new Option("Austria", "austria"),
        new Option("Azerbaijan", "azerbaijan"),
        new Option("Bahamas", "bahamas"),
        new Option("Bahrain", "bahrain"),
        new Option("Bangladesh", "bangladesh"),
        new Option("Barbados", "barbados"),
        new Option("Belarus", "belarus"),
        new Option("Belgium", "belgium"),
        new Option("Belize", "belize"),
        new Option("Benin", "benin"),
        new Option("Bermuda", "bermuda"),
        new Option("Bhutan", "bhutan"),
        new Option("Bolivia", "bolivia"),
        new Option("Bosnia and Herzegovina", "bosnia_and_herzegovina"),
        new Option("Botswana", "botswana"),
        new Option("Brazil", "brazil"),
        new Option("British Indian Ocean Territory", "british_indian_ocean_territory"),
        new Option("Brunei Darussalam", "brunei_darussalam"),
        new Option("Bulgaria", "bulgaria"),
        new Option("Burkina Faso", "burkina_faso"),
        new Option("Burundi", "burundi"),
        new Option("Cambodia", "cambodia"),
        new Option("Cameroon", "cameroon"),
        new Option("Canada", "canada"),
        new Option("Cape Verde", "cape_verde"),
        new Option("Cayman Islands", "cayman_islands"),
        new Option("Central African Republic", "central_african_republic"),
        new Option("Chad", "chad"),
        new Option("Chile", "chile"),
        new Option("China", "china"),
        new Option("Christmas Island", "christmas_island"),
        new Option("Cocos (Keeling) Islands", "cocos_islands"),
        new Option("Colombia", "colombia"),
        new Option("Comoros", "comoros"),
        new Option("Congo", "congo"),
        new Option("Cook Islands", "cook_islands"),
        new Option("Costa Rica", "costa_rica"),
        new Option("Cote d'Ivoire", "cote_d_ivoire"),
        new Option("Croatia", "croatia"),
        new Option("Cuba", "cuba"),
        new Option("Cyprus", "cyprus"),
        new Option("Czech Republic", "czech_republic"),
        new Option("Denmark", "denmark"),
        new Option("Djibouti", "djibouti"),
        new Option("Dominica", "dominica"),
        new Option("Dominican Republic", "dominican_republic"),
        new Option("Ecuador", "ecuador"),
        new Option("Egypt", "egypt"),
        new Option("El Salvador", "el_salvador"),
        new Option("Equatorial Guinea", "equatorial_guinea"),
        new Option("Eritrea", "eritrea"),
        new Option("Estonia", "estonia"),
        new Option("Ethiopia", "ethiopia"),
        new Option("Falkland Islands (Malvinas)", "falkland_islands_malvinas"),
        new Option("Faroe Islands", "faroe_islands"),
        new Option("Fiji", "fiji"),
        new Option("Finland", "finland"),
        new Option("France", "france"),
        new Option("French Guiana", "french_guiana"),
        new Option("French Polynesia", "french_polynesia"),
        new Option("French Southern Territories", "french_southern_territories"),
        new Option("Gabon", "gabon"),
        new Option("Gambia", "gambia"),
        new Option("Georgia", "georgia"),
        new Option("Germany", "germany"),
        new Option("Ghana", "ghana"),
        new Option("Gibraltar", "gibraltar"),
        new Option("Greece", "greece"),
        new Option("Greenland", "greenland"),
        new Option("Grenada", "grenada"),
        new Option("Guadeloupe", "guadeloupe"),
        new Option("Guam", "guam"),
        new Option("Guatemala", "guatemala"),
        new Option("Guernsey", "guernsey"),
        new Option("Guinea", "guinea"),
        new Option("Guinea-Bissau", "guinea-bissau"),
        new Option("Guyana", "guyana"),
        new Option("Haiti", "haiti"),
        new Option("Heard Island and McDonald Islands", "heard_island_and_mcdonald_islands"),
        new Option("Holy See (Vatican City State)", "holy_see_vatican_city_state"),
        new Option("Honduras", "honduras"),
        new Option("Hong Kong", "hong_kong"),
        new Option("Hungary", "hungary"),
        new Option("Iceland", "iceland"),
        new Option("India", "india"),
        new Option("Indonesia", "indonesia"),
        new Option("Iran", "iran"),
        new Option("Iraq", "iraq"),
        new Option("Ireland", "ireland"),
        new Option("Isle of Man", "isle_of_man"),
        new Option("Israel", "israel"),
        new Option("Italy", "italy"),
        new Option("Jamaica", "jamaica"),
        new Option("Japan", "japan"),
        new Option("Jersey", "jersey"),
        new Option("Jordan", "jordan"),
        new Option("Kazakhstan", "kazakhstan"),
        new Option("Kenya", "kenya"),
        new Option("Kiribati", "kiribati"),
        new Option("Kuwait", "kuwait"),
        new Option("Kyrgyzstan", "kyrgyzstan"),
        new Option("Laos", "laos"),
        new Option("Latvia", "latvia"),
        new Option("Lebanon", "lebanon"),
        new Option("Lesotho", "lesotho"),
        new Option("Liberia", "liberia"),
        new Option("Libya", "libya"),
        new Option("Liechtenstein", "liechtenstein"),
        new Option("Lithuania", "lithuania"),
        new Option("Luxembourg", "luxembourg"),
        new Option("Macao", "macao"),
        new Option("Macedonia", "macedonia"),
        new Option("Madagascar", "madagascar"),
        new Option("Malawi", "malawi"),
        new Option("Malaysia", "malaysia"),
        new Option("Maldives", "maldives"),
        new Option("Mali", "mali"),
        new Option("Malta", "malta"),
        new Option("Marshall Islands", "marshall_islands"),
        new Option("Martinique", "martinique"),
        new Option("Mauritania", "mauritania"),
        new Option("Mauritius", "mauritius"),
        new Option("Mayotte", "mayotte"),
        new Option("Mexico", "mexico"),
        new Option("Micronesia", "micronesia"),
        new Option("Moldova", "moldova"),
        new Option("Monaco", "monaco"),
        new Option("Mongolia", "mongolia"),
        new Option("Montenegro", "montenegro"),
        new Option("Montserrat", "montserrat"),
        new Option("Morocco", "morocco"),
        new Option("Mozambique", "mozambique"),
        new Option("Myanmar", "myanmar"),
        new Option("Namibia", "namibia"),
        new Option("Nauru", "nauru"),
        new Option("Nepal", "nepal"),
        new Option("Netherlands", "netherlands"),
        new Option("Netherlands Antilles", "netherlands_antilles"),
        new Option("New Caledonia", "new_caledonia"),
        new Option("New Zealand", "new_zealand"),
        new Option("Nicaragua", "nicaragua"),
        new Option("Niger", "niger"),
        new Option("Nigeria", "nigeria"),
        new Option("Niue", "niue"),
        new Option("Norfolk Island", "norfolk_island"),
        new Option("Northern Mariana Islands", "northern_mariana_islands"),
        new Option("Norway", "norway"),
        new Option("Oman", "oman"),
        new Option("Pakistan", "pakistan"),
        new Option("Palau", "palau"),
        new Option("Palestine", "palestine"),
        new Option("Panama", "panama"),
        new Option("Papua New Guinea", "papua_new_guinea"),
        new Option("Paraguay", "paraguay"),
        new Option("Peru", "peru"),
        new Option("Philippines", "philippines"),
        new Option("Pitcairn Islands", "pitcairn_islands"),
        new Option("Poland", "poland"),
        new Option("Portugal", "portugal"),
        new Option("Puerto Rico", "puerto_rico"),
        new Option("Qatar", "qatar"),
        new Option("Reunion", "reunion"),
        new Option("Romania", "romania"),
        new Option("Russian Federation", "russian_federation"),
        new Option("Rwanda", "rwanda"),
        new Option("Saint Kitts and Nevis", "saint_kitts_and_nevis"),
        new Option("Saint Lucia", "saint_lucia"),
        new Option("Saint Vincent and the Grenadines", "saint_vincent_and_the_grenadines"),
        new Option("Samoa", "samoa"),
        new Option("San Marino", "san_marino"),
        new Option("Sao Tome and Principe", "sao_tome_and_principe"),
        new Option("Saudi Arabia", "saudi_arabia"),
        new Option("Senegal", "senegal"),
        new Option("Serbia", "serbia"),
        new Option("Seychelles", "seychelles"),
        new Option("Sierra Leone", "sierra_leone"),
        new Option("Singapore", "singapore"),
        new Option("Slovakia", "slovakia"),
        new Option("Slovenia", "slovenia"),
        new Option("Solomon Islands", "solomon_islands"),
        new Option("Somalia", "somalia"),
        new Option("South Africa", "south_africa"),
        new Option("South Georgia and the South Sandwich Islands", "south_georgia_and_the_south_sandwich_islands"),
        new Option("Spain", "spain"),
        new Option("Sri Lanka", "sri_lanka"),
        new Option("Sudan", "sudan"),
        new Option("Suriname", "suriname"),
        new Option("Svalbard and Jan Mayen", "svalbard_and_jan_mayen"),
        new Option("Swaziland", "swaziland"),
        new Option("Sweden", "sweden"),
        new Option("Switzerland", "switzerland"),
        new Option("Syrian Arab Republic", "syrian_arab_republic"),
        new Option("Taiwan", "taiwan"),
        new Option("Tajikistan", "tajikistan"),
        new Option("Tanzania", "tanzania"),
        new Option("Thailand", "thailand"),
        new Option("Timor-Leste", "timor-leste"),
        new Option("Togo", "togo"),
        new Option("Tokelau", "tokelau"),
        new Option("Tonga", "tonga"),
        new Option("Trinidad and Tobago", "trinidad_and_tobago"),
        new Option("Tunisia", "tunisia"),
        new Option("Turkey", "turkey"),
        new Option("Turkmenistan", "turkmenistan"),
        new Option("Turks and Caicos Islands", "turks_and_caicos_islands"),
        new Option("Tuvalu", "tuvalu"),
        new Option("Uganda", "uganda"),
        new Option("Ukraine", "ukraine"),
        new Option("United Arab Emirates", "united_arab_emirates"),
        new Option("United Kingdom", "united_kingdom"),
        new Option("United States", "united_states"),
        new Option("Uruguay", "uruguay"),
        new Option("Uzbekistan", "uzbekistan"),
        new Option("Vanuatu", "vanuatu"),
        new Option("Venezuela", "venezuela"),
        new Option("Vietnam", "vietnam"),
        new Option("Yemen", "yemen"),
        new Option("Zambia", "zambia"),
        new Option("Zimbabwe", "zimbabwe"),
        new Option("Åland Islands", "åland_islands")
    ]
}

function getOptions(name) {
    if (name in options) {
        return options[name];
    }
    return options.default;
}

export { getOptions };